#!/bin/bash

PATH='/bin:/sbin:/usr/bin:/usr/sbin'

HOST_DOMAIN="schaeferzone.net"
HOST_NAME="`hostname --short`.$HOST_DOMAIN"
MASTER_HOST_NAME="big-bang.schaeferzone.net"
MASTER_IP="192.168.10.5"

function check_hostname() {
	require_reboot=0

	ping -c 3 $HOST_NAME &> /dev/null
	if [ $? -ne 0 ]; then
		echo "Adding a /etc/hosts record for $HOST_NAME"
		echo -e "127.0.1.1\t$HOST_NAME" | sudo tee --append /etc/hosts
		require_reboot=1
		ping -c 3 $HOST_NAME &> /dev/null
		if [ $? -ne 0 ]; then
			echo "Unable to apply the FQDN of the host"
			exit 1
		fi
	fi

	if [ "`hostname`" != "$HOST_NAME" ]; then
		echo "Setting the hostname of the machine to $HOST_NAME"
		echo $HOST_NAME | sudo tee /etc/hostname
		sudo hostname $HOST_NAME
		require_reboot=1
	fi

	if [ $require_reboot -eq 1 ]; then
		echo "To continue with the bootstrap process, the machine needs to reboot."
		echo "After rebooting, please run this script again to continue the bootstrap process"
		exit 1
	fi
}

function check_master_connection() {
	ping -c 3 $MASTER_HOST_NAME &> /dev/null
	if [ $? -ne 0 ]; then
		echo "Adding a static /etc/hosts record for $MASTER_HOST_NAME"
		echo -e "$MASTER_IP\t$MASTER_HOST_NAME" | sudo tee --append /etc/hosts
		ping -c 3 $MASTER_HOST_NAME &> /dev/null
		if [ $? -ne 0 ]; then
			echo "Unable to reach the Puppet Master"
			exit 1
		fi
	fi
}

function install_dependencies() {
	echo "Installing python-software-properties"
	sudo apt-get -y install python-software-properties > /dev/null
	if [ ${?} -ne 0 ]; then
		echo "Something went wrong with installing python-software-properties."
		exit 1
	fi
}

function install_puppetagent() {
	echo "Installing Puppetagent"
	sudo apt-get -y install puppet > /dev/null
	if [ ${?} -ne 0 ]; then
		echo "Something went wrong with installing Puppet."
		exit 1
	fi

	sudo /etc/init.d/puppet stop
	if [ ${?} -ne 0 ]; then
		echo "Something went wrong with stopping Puppet."
		exit 1
	fi

	puppet_master=`puppet config print all | grep -e "^server = " | awk '{print $3}'`
	if [ "$puppet_master" != "$MASTER_HOST_NAME" ]; then
		echo "Setting the Agent's master to be $MASTER_HOST_NAME"
		echo "Before continuing, run the following command on $MASTER_HOST_NAME:"
		echo; echo "sudo puppet cert clean $HOST_NAME"
		echo; echo -n "Please press [ENTER] to contunue"
		read
		sudo rm -f /var/lib/puppet/ssl/certs/$HOST_NAME.pem
		sudo puppet agent --test --server $MASTER_HOST_NAME -d
		echo "Please run the following command on $MASTER_HOST_NAME if autosign is disabled:"
		echo; echo "sudo sudo puppet cert sign $HOST_NAME"
		echo; echo -n "Please press [ENTER] to contunue"
		read
		sudo puppet agent --test --server $MASTER_HOST_NAME --waitforcert 30 --pluginsync -d
	fi
}

check_hostname
check_master_connection
install_dependencies
install_puppetagent
